version: '3.9'

services:
    mysql:
        image: mysql:8.0
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: Cinema
            MYSQL_USER: ahnitam
            MYSQL_PASSWORD: ahnitam
            MYSQL_ROOT_HOST: '%'
        volumes:
            - mysql:/var/lib/mysql

volumes:
  mysql:
