/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import cinema.Services;
import java.rmi.RemoteException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import models.Movie;
import models.Session;
import models.Ticket;

/**
 *
 * @author higor
 */
public class ComprarIngressos extends javax.swing.JFrame {

    /**
     * Creates new form ComprarIngressos
     */
    final private Services server;

    public ComprarIngressos(Services server) {
        initComponents();
        this.server = server;
        ListarFilmes();
    }
    
    private void ListarFilmes() {
        DefaultComboBoxModel dados = (DefaultComboBoxModel) combo_filmes.getModel();
        dados.removeAllElements();
        dados.addElement("Selecione um filme");
        try {
            List<Movie> FilmeList = server.listarFilmesDisponiveis();
            FilmeList.forEach(filme -> {
            dados.addElement(filme);
        });
        } catch (RemoteException ex) {
            Logger.getLogger(ComprarIngressos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ListarSessoes(Movie movie) {
        DefaultComboBoxModel dados = (DefaultComboBoxModel) combo_sessoes.getModel();
        dados.removeAllElements();
        dados.addElement("Selecione uma sessão");
        try {
            List<Session> SessaoList = server.listarSessaoDisponivel(movie);
            SessaoList.forEach(sessao -> {
            dados.addElement(sessao);
        });
        } catch (RemoteException ex) {
            Logger.getLogger(ComprarIngressos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ListarIngressos(Session sessao) {
        DefaultComboBoxModel dados = (DefaultComboBoxModel) combo_ingressos.getModel();
        dados.removeAllElements();
        dados.addElement("Selecione um ingresso");
        try {
            List<Ticket> ingressoList = server.listarIngressosDisponiveis(sessao);
            ingressoList.forEach(ingresso -> {
            dados.addElement(ingresso);
        });
        } catch (RemoteException ex) {
            Logger.getLogger(ComprarIngressos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_filmes = new javax.swing.JComboBox<>();
        combo_sessoes = new javax.swing.JComboBox<>();
        combo_ingressos = new javax.swing.JComboBox<>();
        btn_voltar = new javax.swing.JButton();
        btn_voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comprar Ingressos");
        setMinimumSize(new java.awt.Dimension(387, 392));
        setResizable(false);
        setSize(new java.awt.Dimension(387, 392));

        combo_filmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um filme" }));
        combo_filmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_filmesItemStateChanged(evt);
            }
        });

        combo_sessoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma sessão" }));
        combo_sessoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_sessoesItemStateChanged(evt);
            }
        });

        combo_ingressos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um ingresso" }));

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_voltar1.setText("Reservar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 93, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo_ingressos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_sessoes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_filmes, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_voltar1)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(combo_filmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_sessoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_ingressos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_voltar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btn_voltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combo_filmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_filmesItemStateChanged
        if (combo_filmes.getSelectedIndex() != 0 && combo_filmes.getSelectedIndex() != -1){
            Movie filme = (Movie) combo_filmes.getSelectedItem();
            ListarSessoes(filme);
        }
    }//GEN-LAST:event_combo_filmesItemStateChanged

    private void combo_sessoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_sessoesItemStateChanged
        if (combo_sessoes.getSelectedIndex() != 0 && combo_sessoes.getSelectedIndex() != -1){
            Session sessao = (Session) combo_sessoes.getSelectedItem();
            ListarIngressos(sessao);
        }
    }//GEN-LAST:event_combo_sessoesItemStateChanged

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        new Inicio(server).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JButton btn_voltar1;
    private javax.swing.JComboBox<Object> combo_filmes;
    private javax.swing.JComboBox<Object> combo_ingressos;
    private javax.swing.JComboBox<Object> combo_sessoes;
    // End of variables declaration//GEN-END:variables

}
